#!/bin/bash

set -eo pipefail

rm -rf tmp/
mkdir -p tmp/

if [[ ! -f compile_flags.txt ]]; then
    scripts/gen_compile_flags  > compile_flags.txt
fi

./util/conv.py misc/smbdis.asm

LIST=$(ls -1 emu/*.cc util/*.cc main.cc)

set -e
set -x

echo $LIST | xargs -n1 -P6 ./scripts/cxx-compile

cat tmp/main.ll | { egrep -A1 'tail call void .*VBlank1.*' || true ; }
cat tmp/main.s | { egrep '\sb\s.*VBlank1.*' || true ; }
./scripts/cxx-link $(find tmp/ -type f -name \*\.o)
