#!/bin/bash

set -e

if [[ ! -f compile_flags.txt ]]; then
    scripts/gen_compile_flags  > compile_flags.txt
fi

./util/conv.py misc/smbdis.asm

LIST=$(ls -1 emu/*.cc util/*.cc main.cc)

set -e
set -x

echo $LIST | xargs -n1 -P6 ./scripts/cxx-compile

./scripts/cxx-link $(find . -type f -name \*\.cc\.o)
