#pragma once
#include "util/base.h"


struct G {
    byte space[32768];
    byte const VRAM_AddrTable_Low[19];
    byte const VRAM_AddrTable_High[19];
    byte const VRAM_Buffer_Offset[2];
    byte const WSelectBufferTemplate[6];
    byte const MushroomIconData[8];
    byte const DemoActionData[21];
    byte const DemoTimingData[22];
    byte const FloateyNumTileData[24];
    byte const ScoreUpdateData[12];
    byte const AreaPalette[4];
    byte const BGColorCtrl_Addr[4];
    byte const BackgroundColors[8];
    byte const PlayerColors[12];
    byte const GameText[1];
    byte const TopStatusBarLine[39];
    byte const WorldLivesDisplay[31];
    byte const TwoPlayerTimeUp[8];
    byte const OnePlayerTimeUp[11];
    byte const TwoPlayerGameOver[8];
    byte const OnePlayerGameOver[13];
    byte const WarpZoneWelcome[45];
    byte const LuigiName[5];
    byte const WarpZoneNumbers[12];
    byte const GameTextOffsets[10];
    byte const ColorRotatePalette[6];
    byte const BlankPalette[8];
    byte const Palette3Data[16];
    byte const BlockGfxData[20];
    byte const MetatileGraphics_Low[4];
    byte const MetatileGraphics_High[4];
    byte const Palette0_MTiles[156];
    byte const Palette1_MTiles[184];
    byte const Palette2_MTiles[40];
    byte const Palette3_MTiles[24];
    byte const WaterPaletteData[36];
    byte const GroundPaletteData[36];
    byte const UndergroundPaletteData[36];
    byte const CastlePaletteData[36];
    byte const DaySnowPaletteData[8];
    byte const NightSnowPaletteData[8];
    byte const MushroomPaletteData[8];
    byte const BowserPaletteData[8];
    byte const MarioThanksMessage[20];
    byte const LuigiThanksMessage[20];
    byte const MushroomRetainerSaved[44];
    byte const PrincessSaved1[23];
    byte const PrincessSaved2[31];
    byte const WorldSelectMessage1[17];
    byte const WorldSelectMessage2[21];
    byte const StatusBarData[12];
    byte const StatusBarOffset[6];
    byte const DefaultSprOffsets[15];
    byte const Sprite0Data[4];
    byte const MusicSelectData[6];
    byte const PlayerStarting_X_Pos[4];
    byte const AltYPosOffset[2];
    byte const PlayerStarting_Y_Pos[9];
    byte const PlayerBGPriorityData[8];
    byte const GameTimerData[4];
    byte const HalfwayPageNybbles[16];
    byte const BSceneDataOffsets[3];
    byte const BackSceneryData[144];
    byte const BackSceneryMetatiles[36];
    byte const FSceneDataOffsets[3];
    byte const ForeSceneryData[39];
    byte const TerrainMetatiles[4];
    byte const TerrainRenderBits[32];
    byte const BlockBuffLowBounds[4];
    byte const FrenzyIDData[3];
    byte const PulleyRopeMetatiles[3];
    byte const CastleMetatiles[55];
    byte const SidePipeShaftData[4];
    byte const SidePipeTopPart[4];
    byte const SidePipeBottomPart[4];
    byte const VerticalPipeData[8];
    byte const CoinMetatileData[4];
    byte const C_ObjectRow[3];
    byte const C_ObjectMetatile[3];
    byte const SolidBlockMetatiles[4];
    byte const BrickMetatiles[5];
    byte const StaircaseHeightData[9];
    byte const StaircaseRowData[9];
    byte const HoleMetatiles[4];
    byte const BlockBufferAddr[4];
    byte const AreaDataOfsLoopback[11];
    byte const WorldAddrOffsets[8];
    byte const AreaAddrOffsets[1];
    byte const World1Areas[5];
    byte const World2Areas[5];
    byte const World3Areas[4];
    byte const World4Areas[5];
    byte const World5Areas[4];
    byte const World6Areas[4];
    byte const World7Areas[5];
    byte const World8Areas[4];
    byte const EnemyAddrHOffsets[4];
    byte const EnemyDataAddrLow[34];
    byte const EnemyDataAddrHigh[34];
    byte const AreaDataHOffsets[4];
    byte const AreaDataAddrLow[34];
    byte const AreaDataAddrHigh[34];
    byte const E_CastleArea1[39];
    byte const E_CastleArea2[25];
    byte const E_CastleArea3[47];
    byte const E_CastleArea4[43];
    byte const E_CastleArea5[21];
    byte const E_CastleArea6[58];
    byte const E_GroundArea1[37];
    byte const E_GroundArea2[29];
    byte const E_GroundArea3[14];
    byte const E_GroundArea4[39];
    byte const E_GroundArea5[49];
    byte const E_GroundArea6[30];
    byte const E_GroundArea7[29];
    byte const E_GroundArea8[21];
    byte const E_GroundArea9[42];
    byte const E_GroundArea10[1];
    byte const E_GroundArea11[36];
    byte const E_GroundArea12[9];
    byte const E_GroundArea13[37];
    byte const E_GroundArea14[35];
    byte const E_GroundArea15[9];
    byte const E_GroundArea16[1];
    byte const E_GroundArea17[58];
    byte const E_GroundArea18[43];
    byte const E_GroundArea19[46];
    byte const E_GroundArea20[28];
    byte const E_GroundArea21[9];
    byte const E_GroundArea22[37];
    byte const E_UndergroundArea1[45];
    byte const E_UndergroundArea2[46];
    byte const E_UndergroundArea3[45];
    byte const E_WaterArea1[17];
    byte const E_WaterArea2[42];
    byte const E_WaterArea3[20];
    byte const L_CastleArea1[97];
    byte const L_CastleArea2[127];
    byte const L_CastleArea3[115];
    byte const L_CastleArea4[109];
    byte const L_CastleArea5[139];
    byte const L_CastleArea6[113];
    byte const L_GroundArea1[99];
    byte const L_GroundArea2[105];
    byte const L_GroundArea3[83];
    byte const L_GroundArea4[143];
    byte const L_GroundArea5[117];
    byte const L_GroundArea6[101];
    byte const L_GroundArea7[85];
    byte const L_GroundArea8[133];
    byte const L_GroundArea9[101];
    byte const L_GroundArea10[9];
    byte const L_GroundArea11[63];
    byte const L_GroundArea12[21];
    byte const L_GroundArea13[103];
    byte const L_GroundArea14[101];
    byte const L_GroundArea15[115];
    byte const L_GroundArea16[49];
    byte const L_GroundArea17[147];
    byte const L_GroundArea18[115];
    byte const L_GroundArea19[121];
    byte const L_GroundArea20[89];
    byte const L_GroundArea21[43];
    byte const L_GroundArea22[51];
    byte const L_UndergroundArea1[163];
    byte const L_UndergroundArea2[161];
    byte const L_UndergroundArea3[141];
    byte const L_WaterArea1[63];
    byte const L_WaterArea2[123];
    byte const L_WaterArea3[28];
    byte const X_SubtracterData[2];
    byte const OffscrJoypadBitsData[2];
    byte const Hidden1UpCoinAmts[8];
    byte const ClimbAdderLow[4];
    byte const ClimbAdderHigh[4];
    byte const JumpMForceData[7];
    byte const FallMForceData[7];
    byte const PlayerYSpdData[7];
    byte const InitMForceData[7];
    byte const MaxLeftXSpdData[3];
    byte const MaxRightXSpdData[4];
    byte const FrictionData[3];
    byte const Climb_Y_SpeedData[3];
    byte const Climb_Y_MForceData[3];
    byte const PlayerAnimTmrData[3];
    byte const FireballXSpdData[2];
    byte const Bubble_MForceData[2];
    byte const BubbleTimerData[2];
    byte const FlagpoleScoreMods[5];
    byte const FlagpoleScoreDigits[5];
    byte const Jumpspring_Y_PosData[4];
    byte const VineHeightData[2];
    byte const CannonBitmasks[2];
    byte const BulletBillXSpdData[2];
    byte const HammerEnemyOfsData[9];
    byte const HammerXSpdData[2];
    byte const CoinTallyOffsets[2];
    byte const ScoreOffsets[2];
    byte const StatusBarNybbles[2];
    byte const BlockYPosAdderData[2];
    byte const BrickQBlockMetatiles[14];
    byte const MaxSpdBlockData[2];
    byte const LoopCmdWorldNumber[11];
    byte const LoopCmdPageNumber[11];
    byte const LoopCmdYPosition[11];
    byte const NormalXSpdData[2];
    byte const HBroWalkingTimerData[2];
    byte const PRDiffAdjustData[12];
    byte const FirebarSpinSpdData[5];
    byte const FirebarSpinDirData[5];
    byte const FlyCCXPositionData[16];
    byte const FlyCCXSpeedData[12];
    byte const FlyCCTimerData[4];
    byte const FlameYPosData[4];
    byte const FlameYMFAdderData[2];
    byte const FireworksXPosData[6];
    byte const FireworksYPosData[6];
    byte const Bitmasks[8];
    byte const Enemy17YPosData[8];
    byte const SwimCC_IDData[2];
    byte const PlatPosDataLow[3];
    byte const PlatPosDataHigh[3];
    byte const HammerThrowTmrData[2];
    byte const XSpeedAdderData[4];
    byte const RevivedXSpeed[4];
    byte const HammerBroJumpLData[2];
    byte const BlooberBitmasks[2];
    byte const SwimCCXMoveData[4];
    byte const FirebarPosLookupTbl[99];
    byte const FirebarMirrorData[4];
    byte const FirebarTblOffsets[12];
    byte const FirebarYPos[2];
    byte const PRandomSubtracter[5];
    byte const FlyCCBPriority[5];
    byte const LakituDiffAdj[3];
    byte const BridgeCollapseData[15];
    byte const PRandomRange[4];
    byte const FlameTimerData[8];
    byte const StarFlagYPosAdder[4];
    byte const StarFlagXPosAdder[4];
    byte const StarFlagTileData[4];
    byte const BowserIdentities[8];
    byte const ResidualXSpdData[2];
    byte const KickedShellXSpdData[2];
    byte const DemotedKoopaXSpdData[2];
    byte const KickedShellPtsData[3];
    byte const StompedEnemyPtsData[4];
    byte const RevivalRateData[2];
    byte const SetBitsMask[7];
    byte const ClearBitsMask[7];
    byte const PlayerPosSPlatData[2];
    byte const PlayerBGUpperExtent[2];
    byte const AreaChangeTimerData[2];
    byte const ClimbXPosAdder[2];
    byte const ClimbPLocAdder[2];
    byte const FlagpoleYPosData[5];
    byte const SolidMTileUpperExt[4];
    byte const ClimbMTileUpperExt[4];
    byte const EnemyBGCStateData[6];
    byte const EnemyBGCXSpdData[2];
    byte const BoundBoxCtrlData[48];
    byte const BlockBufferAdderData[3];
    byte const BlockBuffer_X_Adder[28];
    byte const BlockBuffer_Y_Adder[28];
    byte const VineYPosAdder[2];
    byte const FirstSprXPos[4];
    byte const FirstSprYPos[4];
    byte const SecondSprXPos[4];
    byte const SecondSprYPos[4];
    byte const FirstSprTilenum[4];
    byte const SecondSprTilenum[4];
    byte const HammerSprAttrib[4];
    byte const FlagpoleScoreNumTiles[10];
    byte const JumpingCoinTiles[4];
    byte const PowerUpGfxTable[16];
    byte const PowerUpAttributes[4];
    byte const EnemyGraphicsTable[258];
    byte const EnemyGfxTableOffsets[27];
    byte const EnemyAttributeData[27];
    byte const EnemyAnimTimingBMask[2];
    byte const JumpspringFrameOffsets[5];
    byte const DefaultBlockObjTiles[4];
    byte const ExplosionTiles[3];
    byte const PlayerGfxTblOffsets[16];
    byte const PlayerGraphicsTable[208];
    byte const SwimKickTileNum[2];
    byte const IntermediatePlayerData[6];
    byte const ChangeSizeOffsetAdder[20];
    byte const ObjOffsetData[3];
    byte const XOffscreenBitsData[16];
    byte const DefaultXOnscreenOfs[3];
    byte const YOffscreenBitsData[9];
    byte const DefaultYOnscreenOfs[3];
    byte const HighPosUnitData[2];
    byte const SwimStompEnvelopeData[14];
    byte const ExtraLifeFreqData[6];
    byte const PowerUpGrabFreqData[30];
    byte const PUp_VGrow_FreqData[32];
    byte const BrickShatterFreqData[16];
    byte const MusicHeaderData[49];
    byte const TimeRunningOutHdr[5];
    byte const Star_CloudHdr[6];
    byte const EndOfLevelMusHdr[5];
    byte const ResidualHeaderData[5];
    byte const UndergroundMusHdr[5];
    byte const SilenceHdr[4];
    byte const CastleMusHdr[5];
    byte const VictoryMusHdr[5];
    byte const GameOverMusHdr[5];
    byte const WaterMusHdr[6];
    byte const WinCastleMusHdr[5];
    byte const GroundLevelPart1Hdr[6];
    byte const GroundLevelPart2AHdr[6];
    byte const GroundLevelPart2BHdr[6];
    byte const GroundLevelPart2CHdr[6];
    byte const GroundLevelPart3AHdr[6];
    byte const GroundLevelPart3BHdr[6];
    byte const GroundLevelLeadInHdr[6];
    byte const GroundLevelPart4AHdr[6];
    byte const GroundLevelPart4BHdr[6];
    byte const GroundLevelPart4CHdr[6];
    byte const DeathMusHdr[6];
    byte const Star_CloudMData[73];
    byte const GroundM_P1Data[27];
    byte const SilenceData[45];
    byte const GroundM_P2AData[44];
    byte const GroundM_P2BData[40];
    byte const GroundM_P2CData[37];
    byte const GroundM_P3AData[25];
    byte const GroundM_P3BData[30];
    byte const GroundMLdInData[44];
    byte const GroundM_P4AData[38];
    byte const GroundM_P4BData[39];
    byte const DeathMusData[2];
    byte const GroundM_P4CData[48];
    byte const CastleMusData[161];
    byte const GameOverMusData[45];
    byte const TimeRunOutMusData[62];
    byte const WinLevelMusData[97];
    byte const UndergroundMusData[65];
    byte const WaterMusData[255];
    byte const EndOfCastleMusData[119];
    byte const VictoryMusData[56];
    byte const FreqRegLookupTbl[102];
    byte const MusicLengthLookupTbl[48];
    byte const EndOfCastleMusicEnvData[4];
    byte const AreaMusicEnvData[8];
    byte const WaterEventMusEnvData[40];
    byte const BowserFlameEnvData[32];
    byte const BrickShatterEnvData[16];
} __attribute__((__packed__));
extern G g;

struct K {
    static constexpr word const PPU_CTRL_REG1 = word(0x2000);
    static constexpr word const PPU_CTRL_REG2 = word(0x2001);
    static constexpr word const PPU_STATUS = word(0x2002);
    static constexpr word const PPU_SPR_ADDR = word(0x2003);
    static constexpr word const PPU_SPR_DATA = word(0x2004);
    static constexpr word const PPU_SCROLL_REG = word(0x2005);
    static constexpr word const PPU_ADDRESS = word(0x2006);
    static constexpr word const PPU_DATA = word(0x2007);
    static constexpr word const SND_REGISTER = word(0x4000);
    static constexpr word const SND_SQUARE1_REG = word(0x4000);
    static constexpr word const SND_SQUARE2_REG = word(0x4004);
    static constexpr word const SND_TRIANGLE_REG = word(0x4008);
    static constexpr word const SND_NOISE_REG = word(0x400c);
    static constexpr word const SND_DELTA_REG = word(0x4010);
    static constexpr word const SND_MASTERCTRL_REG = word(0x4015);
    static constexpr word const SPR_DMA = word(0x4014);
    static constexpr word const JOYPAD_PORT = word(0x4016);
    static constexpr word const JOYPAD_PORT1 = word(0x4016);
    static constexpr word const JOYPAD_PORT2 = word(0x4017);
    static constexpr byte const ObjectOffset = byte(0x8);
    static constexpr byte const FrameCounter = byte(0x9);
    static constexpr word const SavedJoypadBits = word(0x6fc);
    static constexpr word const SavedJoypad1Bits = word(0x6fc);
    static constexpr word const SavedJoypad2Bits = word(0x6fd);
    static constexpr word const JoypadBitMask = word(0x74a);
    static constexpr word const JoypadOverride = word(0x758);
    static constexpr byte const A_B_Buttons = byte(0xa);
    static constexpr byte const PreviousA_B_Buttons = byte(0xd);
    static constexpr byte const Up_Down_Buttons = byte(0xb);
    static constexpr byte const Left_Right_Buttons = byte(0xc);
    static constexpr byte const GameEngineSubroutine = byte(0xe);
    static constexpr word const Mirror_PPU_CTRL_REG1 = word(0x778);
    static constexpr word const Mirror_PPU_CTRL_REG2 = word(0x779);
    static constexpr word const OperMode = word(0x770);
    static constexpr word const OperMode_Task = word(0x772);
    static constexpr word const ScreenRoutineTask = word(0x73c);
    static constexpr word const GamePauseStatus = word(0x776);
    static constexpr word const GamePauseTimer = word(0x777);
    static constexpr word const DemoAction = word(0x717);
    static constexpr word const DemoActionTimer = word(0x718);
    static constexpr word const TimerControl = word(0x747);
    static constexpr word const IntervalTimerControl = word(0x77f);
    static constexpr word const Timers = word(0x780);
    static constexpr word const SelectTimer = word(0x780);
    static constexpr word const PlayerAnimTimer = word(0x781);
    static constexpr word const JumpSwimTimer = word(0x782);
    static constexpr word const RunningTimer = word(0x783);
    static constexpr word const BlockBounceTimer = word(0x784);
    static constexpr word const SideCollisionTimer = word(0x785);
    static constexpr word const JumpspringTimer = word(0x786);
    static constexpr word const GameTimerCtrlTimer = word(0x787);
    static constexpr word const ClimbSideTimer = word(0x789);
    static constexpr word const EnemyFrameTimer = word(0x78a);
    static constexpr word const FrenzyEnemyTimer = word(0x78f);
    static constexpr word const BowserFireBreathTimer = word(0x790);
    static constexpr word const StompTimer = word(0x791);
    static constexpr word const AirBubbleTimer = word(0x792);
    static constexpr word const ScrollIntervalTimer = word(0x795);
    static constexpr word const EnemyIntervalTimer = word(0x796);
    static constexpr word const BrickCoinTimer = word(0x79d);
    static constexpr word const InjuryTimer = word(0x79e);
    static constexpr word const StarInvincibleTimer = word(0x79f);
    static constexpr word const ScreenTimer = word(0x7a0);
    static constexpr word const WorldEndTimer = word(0x7a1);
    static constexpr word const DemoTimer = word(0x7a2);
    static constexpr word const Sprite_Data = word(0x200);
    static constexpr word const Sprite_Y_Position = word(0x200);
    static constexpr word const Sprite_Tilenumber = word(0x201);
    static constexpr word const Sprite_Attributes = word(0x202);
    static constexpr word const Sprite_X_Position = word(0x203);
    static constexpr word const ScreenEdge_PageLoc = word(0x71a);
    static constexpr word const ScreenEdge_X_Pos = word(0x71c);
    static constexpr word const ScreenLeft_PageLoc = word(0x71a);
    static constexpr word const ScreenRight_PageLoc = word(0x71b);
    static constexpr word const ScreenLeft_X_Pos = word(0x71c);
    static constexpr word const ScreenRight_X_Pos = word(0x71d);
    static constexpr byte const PlayerFacingDir = byte(0x33);
    static constexpr byte const DestinationPageLoc = byte(0x34);
    static constexpr byte const VictoryWalkControl = byte(0x35);
    static constexpr word const ScrollFractional = word(0x768);
    static constexpr word const PrimaryMsgCounter = word(0x719);
    static constexpr word const SecondaryMsgCounter = word(0x749);
    static constexpr word const HorizontalScroll = word(0x73f);
    static constexpr word const VerticalScroll = word(0x740);
    static constexpr word const ScrollLock = word(0x723);
    static constexpr word const ScrollThirtyTwo = word(0x73d);
    static constexpr word const Player_X_Scroll = word(0x6ff);
    static constexpr word const Player_Pos_ForScroll = word(0x755);
    static constexpr word const ScrollAmount = word(0x775);
    static constexpr byte const AreaData = byte(0xe7);
    static constexpr byte const AreaDataLow = byte(0xe7);
    static constexpr byte const AreaDataHigh = byte(0xe8);
    static constexpr byte const EnemyData = byte(0xe9);
    static constexpr byte const EnemyDataLow = byte(0xe9);
    static constexpr byte const EnemyDataHigh = byte(0xea);
    static constexpr word const AreaParserTaskNum = word(0x71f);
    static constexpr word const ColumnSets = word(0x71e);
    static constexpr word const CurrentPageLoc = word(0x725);
    static constexpr word const CurrentColumnPos = word(0x726);
    static constexpr word const BackloadingFlag = word(0x728);
    static constexpr word const BehindAreaParserFlag = word(0x729);
    static constexpr word const AreaObjectPageLoc = word(0x72a);
    static constexpr word const AreaObjectPageSel = word(0x72b);
    static constexpr word const AreaDataOffset = word(0x72c);
    static constexpr word const AreaObjOffsetBuffer = word(0x72d);
    static constexpr word const AreaObjectLength = word(0x730);
    static constexpr word const StaircaseControl = word(0x734);
    static constexpr word const AreaObjectHeight = word(0x735);
    static constexpr word const MushroomLedgeHalfLen = word(0x736);
    static constexpr word const EnemyDataOffset = word(0x739);
    static constexpr word const EnemyObjectPageLoc = word(0x73a);
    static constexpr word const EnemyObjectPageSel = word(0x73b);
    static constexpr word const MetatileBuffer = word(0x6a1);
    static constexpr word const BlockBufferColumnPos = word(0x6a0);
    static constexpr word const CurrentNTAddr_Low = word(0x721);
    static constexpr word const CurrentNTAddr_High = word(0x720);
    static constexpr word const AttributeBuffer = word(0x3f9);
    static constexpr word const LoopCommand = word(0x745);
    static constexpr word const DisplayDigits = word(0x7d7);
    static constexpr word const TopScoreDisplay = word(0x7d7);
    static constexpr word const ScoreAndCoinDisplay = word(0x7dd);
    static constexpr word const PlayerScoreDisplay = word(0x7dd);
    static constexpr word const GameTimerDisplay = word(0x7f8);
    static constexpr word const DigitModifier = word(0x134);
    static constexpr word const VerticalFlipFlag = word(0x109);
    static constexpr word const FloateyNum_Control = word(0x110);
    static constexpr word const ShellChainCounter = word(0x125);
    static constexpr word const FloateyNum_Timer = word(0x12c);
    static constexpr word const FloateyNum_X_Pos = word(0x117);
    static constexpr word const FloateyNum_Y_Pos = word(0x11e);
    static constexpr word const FlagpoleFNum_Y_Pos = word(0x10d);
    static constexpr word const FlagpoleFNum_YMFDummy = word(0x10e);
    static constexpr word const FlagpoleScore = word(0x10f);
    static constexpr word const FlagpoleCollisionYPos = word(0x70f);
    static constexpr word const StompChainCounter = word(0x484);
    static constexpr word const VRAM_Buffer1_Offset = word(0x300);
    static constexpr word const VRAM_Buffer1 = word(0x301);
    static constexpr word const VRAM_Buffer2_Offset = word(0x340);
    static constexpr word const VRAM_Buffer2 = word(0x341);
    static constexpr word const VRAM_Buffer_AddrCtrl = word(0x773);
    static constexpr word const Sprite0HitDetectFlag = word(0x722);
    static constexpr word const DisableScreenFlag = word(0x774);
    static constexpr word const DisableIntermediate = word(0x769);
    static constexpr word const ColorRotateOffset = word(0x6d4);
    static constexpr word const TerrainControl = word(0x727);
    static constexpr word const AreaStyle = word(0x733);
    static constexpr word const ForegroundScenery = word(0x741);
    static constexpr word const BackgroundScenery = word(0x742);
    static constexpr word const CloudTypeOverride = word(0x743);
    static constexpr word const BackgroundColorCtrl = word(0x744);
    static constexpr word const AreaType = word(0x74e);
    static constexpr word const AreaAddrsLOffset = word(0x74f);
    static constexpr word const AreaPointer = word(0x750);
    static constexpr word const PlayerEntranceCtrl = word(0x710);
    static constexpr word const GameTimerSetting = word(0x715);
    static constexpr word const AltEntranceControl = word(0x752);
    static constexpr word const EntrancePage = word(0x751);
    static constexpr word const NumberOfPlayers = word(0x77a);
    static constexpr word const WarpZoneControl = word(0x6d6);
    static constexpr word const ChangeAreaTimer = word(0x6de);
    static constexpr word const MultiLoopCorrectCntr = word(0x6d9);
    static constexpr word const MultiLoopPassCntr = word(0x6da);
    static constexpr word const FetchNewGameTimerFlag = word(0x757);
    static constexpr word const GameTimerExpiredFlag = word(0x759);
    static constexpr word const PrimaryHardMode = word(0x76a);
    static constexpr word const SecondaryHardMode = word(0x6cc);
    static constexpr word const WorldSelectNumber = word(0x76b);
    static constexpr word const WorldSelectEnableFlag = word(0x7fc);
    static constexpr word const ContinueWorld = word(0x7fd);
    static constexpr word const CurrentPlayer = word(0x753);
    static constexpr word const PlayerSize = word(0x754);
    static constexpr word const PlayerStatus = word(0x756);
    static constexpr word const OnscreenPlayerInfo = word(0x75a);
    static constexpr word const NumberofLives = word(0x75a);
    static constexpr word const HalfwayPage = word(0x75b);
    static constexpr word const LevelNumber = word(0x75c);
    static constexpr word const Hidden1UpFlag = word(0x75d);
    static constexpr word const CoinTally = word(0x75e);
    static constexpr word const WorldNumber = word(0x75f);
    static constexpr word const AreaNumber = word(0x760);
    static constexpr word const CoinTallyFor1Ups = word(0x748);
    static constexpr word const OffscreenPlayerInfo = word(0x761);
    static constexpr word const OffScr_NumberofLives = word(0x761);
    static constexpr word const OffScr_HalfwayPage = word(0x762);
    static constexpr word const OffScr_LevelNumber = word(0x763);
    static constexpr word const OffScr_Hidden1UpFlag = word(0x764);
    static constexpr word const OffScr_CoinTally = word(0x765);
    static constexpr word const OffScr_WorldNumber = word(0x766);
    static constexpr word const OffScr_AreaNumber = word(0x767);
    static constexpr word const BalPlatformAlignment = word(0x3a0);
    static constexpr word const Platform_X_Scroll = word(0x3a1);
    static constexpr word const PlatformCollisionFlag = word(0x3a2);
    static constexpr word const YPlatformTopYPos = word(0x401);
    static constexpr byte const YPlatformCenterYPos = byte(0x58);
    static constexpr word const BrickCoinTimerFlag = word(0x6bc);
    static constexpr word const StarFlagTaskControl = word(0x746);
    static constexpr word const PseudoRandomBitReg = word(0x7a7);
    static constexpr word const WarmBootValidation = word(0x7ff);
    static constexpr word const SprShuffleAmtOffset = word(0x6e0);
    static constexpr word const SprShuffleAmt = word(0x6e1);
    static constexpr word const SprDataOffset = word(0x6e4);
    static constexpr word const Player_SprDataOffset = word(0x6e4);
    static constexpr word const Enemy_SprDataOffset = word(0x6e5);
    static constexpr word const Block_SprDataOffset = word(0x6ec);
    static constexpr word const Alt_SprDataOffset = word(0x6ec);
    static constexpr word const Bubble_SprDataOffset = word(0x6ee);
    static constexpr word const FBall_SprDataOffset = word(0x6f1);
    static constexpr word const Misc_SprDataOffset = word(0x6f3);
    static constexpr word const SprDataOffset_Ctrl = word(0x3ee);
    static constexpr byte const Player_State = byte(0x1d);
    static constexpr byte const Enemy_State = byte(0x1e);
    static constexpr byte const Fireball_State = byte(0x24);
    static constexpr byte const Block_State = byte(0x26);
    static constexpr byte const Misc_State = byte(0x2a);
    static constexpr byte const Player_MovingDir = byte(0x45);
    static constexpr byte const Enemy_MovingDir = byte(0x46);
    static constexpr byte const SprObject_X_Speed = byte(0x57);
    static constexpr byte const Player_X_Speed = byte(0x57);
    static constexpr byte const Enemy_X_Speed = byte(0x58);
    static constexpr byte const Fireball_X_Speed = byte(0x5e);
    static constexpr byte const Block_X_Speed = byte(0x60);
    static constexpr byte const Misc_X_Speed = byte(0x64);
    static constexpr byte const Jumpspring_FixedYPos = byte(0x58);
    static constexpr word const JumpspringAnimCtrl = word(0x70e);
    static constexpr word const JumpspringForce = word(0x6db);
    static constexpr byte const SprObject_PageLoc = byte(0x6d);
    static constexpr byte const Player_PageLoc = byte(0x6d);
    static constexpr byte const Enemy_PageLoc = byte(0x6e);
    static constexpr byte const Fireball_PageLoc = byte(0x74);
    static constexpr byte const Block_PageLoc = byte(0x76);
    static constexpr byte const Misc_PageLoc = byte(0x7a);
    static constexpr byte const Bubble_PageLoc = byte(0x83);
    static constexpr byte const SprObject_X_Position = byte(0x86);
    static constexpr byte const Player_X_Position = byte(0x86);
    static constexpr byte const Enemy_X_Position = byte(0x87);
    static constexpr byte const Fireball_X_Position = byte(0x8d);
    static constexpr byte const Block_X_Position = byte(0x8f);
    static constexpr byte const Misc_X_Position = byte(0x93);
    static constexpr byte const Bubble_X_Position = byte(0x9c);
    static constexpr byte const SprObject_Y_Speed = byte(0x9f);
    static constexpr byte const Player_Y_Speed = byte(0x9f);
    static constexpr byte const Enemy_Y_Speed = byte(0xa0);
    static constexpr byte const Fireball_Y_Speed = byte(0xa6);
    static constexpr byte const Block_Y_Speed = byte(0xa8);
    static constexpr byte const Misc_Y_Speed = byte(0xac);
    static constexpr byte const SprObject_Y_HighPos = byte(0xb5);
    static constexpr byte const Player_Y_HighPos = byte(0xb5);
    static constexpr byte const Enemy_Y_HighPos = byte(0xb6);
    static constexpr byte const Fireball_Y_HighPos = byte(0xbc);
    static constexpr byte const Block_Y_HighPos = byte(0xbe);
    static constexpr byte const Misc_Y_HighPos = byte(0xc2);
    static constexpr byte const Bubble_Y_HighPos = byte(0xcb);
    static constexpr byte const SprObject_Y_Position = byte(0xce);
    static constexpr byte const Player_Y_Position = byte(0xce);
    static constexpr byte const Enemy_Y_Position = byte(0xcf);
    static constexpr byte const Fireball_Y_Position = byte(0xd5);
    static constexpr byte const Block_Y_Position = byte(0xd7);
    static constexpr byte const Misc_Y_Position = byte(0xdb);
    static constexpr byte const Bubble_Y_Position = byte(0xe4);
    static constexpr word const SprObject_Rel_XPos = word(0x3ad);
    static constexpr word const Player_Rel_XPos = word(0x3ad);
    static constexpr word const Enemy_Rel_XPos = word(0x3ae);
    static constexpr word const Fireball_Rel_XPos = word(0x3af);
    static constexpr word const Bubble_Rel_XPos = word(0x3b0);
    static constexpr word const Block_Rel_XPos = word(0x3b1);
    static constexpr word const Misc_Rel_XPos = word(0x3b3);
    static constexpr word const SprObject_Rel_YPos = word(0x3b8);
    static constexpr word const Player_Rel_YPos = word(0x3b8);
    static constexpr word const Enemy_Rel_YPos = word(0x3b9);
    static constexpr word const Fireball_Rel_YPos = word(0x3ba);
    static constexpr word const Bubble_Rel_YPos = word(0x3bb);
    static constexpr word const Block_Rel_YPos = word(0x3bc);
    static constexpr word const Misc_Rel_YPos = word(0x3be);
    static constexpr word const SprObject_SprAttrib = word(0x3c4);
    static constexpr word const Player_SprAttrib = word(0x3c4);
    static constexpr word const Enemy_SprAttrib = word(0x3c5);
    static constexpr word const SprObject_X_MoveForce = word(0x400);
    static constexpr word const Enemy_X_MoveForce = word(0x401);
    static constexpr word const SprObject_YMF_Dummy = word(0x416);
    static constexpr word const Player_YMF_Dummy = word(0x416);
    static constexpr word const Enemy_YMF_Dummy = word(0x417);
    static constexpr word const Bubble_YMF_Dummy = word(0x42c);
    static constexpr word const SprObject_Y_MoveForce = word(0x433);
    static constexpr word const Player_Y_MoveForce = word(0x433);
    static constexpr word const Enemy_Y_MoveForce = word(0x434);
    static constexpr word const Block_Y_MoveForce = word(0x43c);
    static constexpr word const DisableCollisionDet = word(0x716);
    static constexpr word const Player_CollisionBits = word(0x490);
    static constexpr word const Enemy_CollisionBits = word(0x491);
    static constexpr word const SprObj_BoundBoxCtrl = word(0x499);
    static constexpr word const Player_BoundBoxCtrl = word(0x499);
    static constexpr word const Enemy_BoundBoxCtrl = word(0x49a);
    static constexpr word const Fireball_BoundBoxCtrl = word(0x4a0);
    static constexpr word const Misc_BoundBoxCtrl = word(0x4a2);
    static constexpr word const EnemyFrenzyBuffer = word(0x6cb);
    static constexpr word const EnemyFrenzyQueue = word(0x6cd);
    static constexpr byte const Enemy_Flag = byte(0xf);
    static constexpr byte const Enemy_ID = byte(0x16);
    static constexpr word const PlayerGfxOffset = word(0x6d5);
    static constexpr word const Player_XSpeedAbsolute = word(0x700);
    static constexpr word const FrictionAdderHigh = word(0x701);
    static constexpr word const FrictionAdderLow = word(0x702);
    static constexpr word const RunningSpeed = word(0x703);
    static constexpr word const SwimmingFlag = word(0x704);
    static constexpr word const Player_X_MoveForce = word(0x705);
    static constexpr word const DiffToHaltJump = word(0x706);
    static constexpr word const JumpOrigin_Y_HighPos = word(0x707);
    static constexpr word const JumpOrigin_Y_Position = word(0x708);
    static constexpr word const VerticalForce = word(0x709);
    static constexpr word const VerticalForceDown = word(0x70a);
    static constexpr word const PlayerChangeSizeFlag = word(0x70b);
    static constexpr word const PlayerAnimTimerSet = word(0x70c);
    static constexpr word const PlayerAnimCtrl = word(0x70d);
    static constexpr word const DeathMusicLoaded = word(0x712);
    static constexpr word const FlagpoleSoundQueue = word(0x713);
    static constexpr word const CrouchingFlag = word(0x714);
    static constexpr word const MaximumLeftSpeed = word(0x450);
    static constexpr word const MaximumRightSpeed = word(0x456);
    static constexpr word const SprObject_OffscrBits = word(0x3d0);
    static constexpr word const Player_OffscreenBits = word(0x3d0);
    static constexpr word const Enemy_OffscreenBits = word(0x3d1);
    static constexpr word const FBall_OffscreenBits = word(0x3d2);
    static constexpr word const Bubble_OffscreenBits = word(0x3d3);
    static constexpr word const Block_OffscreenBits = word(0x3d4);
    static constexpr word const Misc_OffscreenBits = word(0x3d6);
    static constexpr word const EnemyOffscrBitsMasked = word(0x3d8);
    static constexpr word const Cannon_Offset = word(0x46a);
    static constexpr word const Cannon_PageLoc = word(0x46b);
    static constexpr word const Cannon_X_Position = word(0x471);
    static constexpr word const Cannon_Y_Position = word(0x477);
    static constexpr word const Cannon_Timer = word(0x47d);
    static constexpr word const Whirlpool_Offset = word(0x46a);
    static constexpr word const Whirlpool_PageLoc = word(0x46b);
    static constexpr word const Whirlpool_LeftExtent = word(0x471);
    static constexpr word const Whirlpool_Length = word(0x477);
    static constexpr word const Whirlpool_Flag = word(0x47d);
    static constexpr word const VineFlagOffset = word(0x398);
    static constexpr word const VineHeight = word(0x399);
    static constexpr word const VineObjOffset = word(0x39a);
    static constexpr word const VineStart_Y_Position = word(0x39d);
    static constexpr word const Block_Orig_YPos = word(0x3e4);
    static constexpr word const Block_BBuf_Low = word(0x3e6);
    static constexpr word const Block_Metatile = word(0x3e8);
    static constexpr word const Block_PageLoc2 = word(0x3ea);
    static constexpr word const Block_RepFlag = word(0x3ec);
    static constexpr word const Block_ResidualCounter = word(0x3f0);
    static constexpr word const Block_Orig_XPos = word(0x3f1);
    static constexpr word const BoundingBox_UL_XPos = word(0x4ac);
    static constexpr word const BoundingBox_UL_YPos = word(0x4ad);
    static constexpr word const BoundingBox_DR_XPos = word(0x4ae);
    static constexpr word const BoundingBox_DR_YPos = word(0x4af);
    static constexpr word const BoundingBox_UL_Corner = word(0x4ac);
    static constexpr word const BoundingBox_LR_Corner = word(0x4ae);
    static constexpr word const EnemyBoundingBoxCoord = word(0x4b0);
    static constexpr byte const PowerUpType = byte(0x39);
    static constexpr byte const FireballBouncingFlag = byte(0x3a);
    static constexpr word const FireballCounter = word(0x6ce);
    static constexpr word const FireballThrowingTimer = word(0x711);
    static constexpr word const HammerEnemyOffset = word(0x6ae);
    static constexpr word const JumpCoinMiscOffset = word(0x6b7);
    static constexpr word const Block_Buffer_1 = word(0x500);
    static constexpr word const Block_Buffer_2 = word(0x5d0);
    static constexpr word const HammerThrowingTimer = word(0x3a2);
    static constexpr byte const HammerBroJumpTimer = byte(0x3c);
    static constexpr word const Misc_Collision_Flag = word(0x6be);
    static constexpr word const RedPTroopaOrigXPos = word(0x401);
    static constexpr byte const RedPTroopaCenterYPos = byte(0x58);
    static constexpr byte const XMovePrimaryCounter = byte(0xa0);
    static constexpr byte const XMoveSecondaryCounter = byte(0x58);
    static constexpr byte const CheepCheepMoveMFlag = byte(0x58);
    static constexpr word const CheepCheepOrigYPos = word(0x434);
    static constexpr word const BitMFilter = word(0x6dd);
    static constexpr word const LakituReappearTimer = word(0x6d1);
    static constexpr byte const LakituMoveSpeed = byte(0x58);
    static constexpr byte const LakituMoveDirection = byte(0xa0);
    static constexpr byte const FirebarSpinState_Low = byte(0x58);
    static constexpr byte const FirebarSpinState_High = byte(0xa0);
    static constexpr word const FirebarSpinSpeed = word(0x388);
    static constexpr byte const FirebarSpinDirection = byte(0x34);
    static constexpr word const DuplicateObj_Offset = word(0x6cf);
    static constexpr word const NumberofGroupEnemies = word(0x6d3);
    static constexpr byte const BlooperMoveCounter = byte(0xa0);
    static constexpr byte const BlooperMoveSpeed = byte(0x58);
    static constexpr word const BowserBodyControls = word(0x363);
    static constexpr word const BowserFeetCounter = word(0x364);
    static constexpr word const BowserMovementSpeed = word(0x365);
    static constexpr word const BowserOrigXPos = word(0x366);
    static constexpr word const BowserFlameTimerCtrl = word(0x367);
    static constexpr word const BowserFront_Offset = word(0x368);
    static constexpr word const BridgeCollapseOffset = word(0x369);
    static constexpr word const BowserGfxFlag = word(0x36a);
    static constexpr word const BowserHitPoints = word(0x483);
    static constexpr word const MaxRangeFromOrigin = word(0x6dc);
    static constexpr word const BowserFlamePRandomOfs = word(0x417);
    static constexpr word const PiranhaPlantUpYPos = word(0x417);
    static constexpr word const PiranhaPlantDownYPos = word(0x434);
    static constexpr byte const PiranhaPlant_Y_Speed = byte(0x58);
    static constexpr byte const PiranhaPlant_MoveFlag = byte(0xa0);
    static constexpr word const FireworksCounter = word(0x6d7);
    static constexpr byte const ExplosionGfxCounter = byte(0x58);
    static constexpr byte const ExplosionTimerCounter = byte(0xa0);
    static constexpr word const Squ2_NoteLenBuffer = word(0x7b3);
    static constexpr word const Squ2_NoteLenCounter = word(0x7b4);
    static constexpr word const Squ2_EnvelopeDataCtrl = word(0x7b5);
    static constexpr word const Squ1_NoteLenCounter = word(0x7b6);
    static constexpr word const Squ1_EnvelopeDataCtrl = word(0x7b7);
    static constexpr word const Tri_NoteLenBuffer = word(0x7b8);
    static constexpr word const Tri_NoteLenCounter = word(0x7b9);
    static constexpr word const Noise_BeatLenCounter = word(0x7ba);
    static constexpr word const Squ1_SfxLenCounter = word(0x7bb);
    static constexpr word const Squ2_SfxLenCounter = word(0x7bd);
    static constexpr word const Sfx_SecondaryCounter = word(0x7be);
    static constexpr word const Noise_SfxLenCounter = word(0x7bf);
    static constexpr byte const PauseSoundQueue = byte(0xfa);
    static constexpr byte const Square1SoundQueue = byte(0xff);
    static constexpr byte const Square2SoundQueue = byte(0xfe);
    static constexpr byte const NoiseSoundQueue = byte(0xfd);
    static constexpr byte const AreaMusicQueue = byte(0xfb);
    static constexpr byte const EventMusicQueue = byte(0xfc);
    static constexpr byte const Square1SoundBuffer = byte(0xf1);
    static constexpr byte const Square2SoundBuffer = byte(0xf2);
    static constexpr byte const NoiseSoundBuffer = byte(0xf3);
    static constexpr byte const AreaMusicBuffer = byte(0xf4);
    static constexpr word const EventMusicBuffer = word(0x7b1);
    static constexpr word const PauseSoundBuffer = word(0x7b2);
    static constexpr byte const MusicData = byte(0xf5);
    static constexpr byte const MusicDataLow = byte(0xf5);
    static constexpr byte const MusicDataHigh = byte(0xf6);
    static constexpr byte const MusicOffset_Square2 = byte(0xf7);
    static constexpr byte const MusicOffset_Square1 = byte(0xf8);
    static constexpr byte const MusicOffset_Triangle = byte(0xf9);
    static constexpr word const MusicOffset_Noise = word(0x7b0);
    static constexpr byte const NoteLenLookupTblOfs = byte(0xf0);
    static constexpr word const DAC_Counter = word(0x7c0);
    static constexpr word const NoiseDataLoopbackOfs = word(0x7c1);
    static constexpr word const NoteLengthTblAdder = word(0x7c4);
    static constexpr word const AreaMusicBuffer_Alt = word(0x7c5);
    static constexpr word const PauseModeFlag = word(0x7c6);
    static constexpr word const GroundMusicHeaderOfs = word(0x7c7);
    static constexpr word const AltRegContentFlag = word(0x7ca);
    static constexpr byte const Sfx_SmallJump = byte(0b10000000);
    static constexpr byte const Sfx_Flagpole = byte(0b1000000);
    static constexpr byte const Sfx_Fireball = byte(0b100000);
    static constexpr byte const Sfx_PipeDown_Injury = byte(0b10000);
    static constexpr byte const Sfx_EnemySmack = byte(0b1000);
    static constexpr byte const Sfx_EnemyStomp = byte(0b100);
    static constexpr byte const Sfx_Bump = byte(0b10);
    static constexpr byte const Sfx_BigJump = byte(0b1);
    static constexpr byte const Sfx_BowserFall = byte(0b10000000);
    static constexpr byte const Sfx_ExtraLife = byte(0b1000000);
    static constexpr byte const Sfx_PowerUpGrab = byte(0b100000);
    static constexpr byte const Sfx_TimerTick = byte(0b10000);
    static constexpr byte const Sfx_Blast = byte(0b1000);
    static constexpr byte const Sfx_GrowVine = byte(0b100);
    static constexpr byte const Sfx_GrowPowerUp = byte(0b10);
    static constexpr byte const Sfx_CoinGrab = byte(0b1);
    static constexpr byte const Sfx_BowserFlame = byte(0b10);
    static constexpr byte const Sfx_BrickShatter = byte(0b1);
    static constexpr byte const Silence = byte(0b10000000);
    static constexpr byte const StarPowerMusic = byte(0b1000000);
    static constexpr byte const PipeIntroMusic = byte(0b100000);
    static constexpr byte const CloudMusic = byte(0b10000);
    static constexpr byte const CastleMusic = byte(0b1000);
    static constexpr byte const UndergroundMusic = byte(0b100);
    static constexpr byte const WaterMusic = byte(0b10);
    static constexpr byte const GroundMusic = byte(0b1);
    static constexpr byte const TimeRunningOutMusic = byte(0b1000000);
    static constexpr byte const EndOfLevelMusic = byte(0b100000);
    static constexpr byte const AltGameOverMusic = byte(0b10000);
    static constexpr byte const EndOfCastleMusic = byte(0b1000);
    static constexpr byte const VictoryMusic = byte(0b100);
    static constexpr byte const GameOverMusic = byte(0b10);
    static constexpr byte const DeathMusic = byte(0b1);
    static constexpr byte const GreenKoopa = byte(0x0);
    static constexpr byte const BuzzyBeetle = byte(0x2);
    static constexpr byte const RedKoopa = byte(0x3);
    static constexpr byte const HammerBro = byte(0x5);
    static constexpr byte const Goomba = byte(0x6);
    static constexpr byte const Bloober = byte(0x7);
    static constexpr byte const BulletBill_FrenzyVar = byte(0x8);
    static constexpr byte const GreyCheepCheep = byte(0xa);
    static constexpr byte const RedCheepCheep = byte(0xb);
    static constexpr byte const Podoboo = byte(0xc);
    static constexpr byte const PiranhaPlant = byte(0xd);
    static constexpr byte const GreenParatroopaJump = byte(0xe);
    static constexpr byte const RedParatroopa = byte(0xf);
    static constexpr byte const GreenParatroopaFly = byte(0x10);
    static constexpr byte const Lakitu = byte(0x11);
    static constexpr byte const Spiny = byte(0x12);
    static constexpr byte const FlyCheepCheepFrenzy = byte(0x14);
    static constexpr byte const FlyingCheepCheep = byte(0x14);
    static constexpr byte const BowserFlame = byte(0x15);
    static constexpr byte const Fireworks = byte(0x16);
    static constexpr byte const BBill_CCheep_Frenzy = byte(0x17);
    static constexpr byte const Stop_Frenzy = byte(0x18);
    static constexpr byte const Bowser = byte(0x2d);
    static constexpr byte const PowerUpObject = byte(0x2e);
    static constexpr byte const VineObject = byte(0x2f);
    static constexpr byte const FlagpoleFlagObject = byte(0x30);
    static constexpr byte const StarFlagObject = byte(0x31);
    static constexpr byte const JumpspringObject = byte(0x32);
    static constexpr byte const BulletBill_CannonVar = byte(0x33);
    static constexpr byte const RetainerObject = byte(0x35);
    static constexpr byte const TallEnemy = byte(0x9);
    static constexpr byte const World1 = byte(0);
    static constexpr byte const World2 = byte(1);
    static constexpr byte const World3 = byte(2);
    static constexpr byte const World4 = byte(3);
    static constexpr byte const World5 = byte(4);
    static constexpr byte const World6 = byte(5);
    static constexpr byte const World7 = byte(6);
    static constexpr byte const World8 = byte(7);
    static constexpr byte const Level1 = byte(0);
    static constexpr byte const Level2 = byte(1);
    static constexpr byte const Level3 = byte(2);
    static constexpr byte const Level4 = byte(3);
    static constexpr byte const WarmBootOffset = byte(LO8(0x7d6));
    static constexpr byte const ColdBootOffset = byte(LO8(0x7fe));
    static constexpr word const TitleScreenDataOffset = word(0x1ec0);
    static constexpr word const SoundMemory = word(0x7b0);
    static constexpr word const SwimTileRepOffset = word(((offsetof(G, PlayerGraphicsTable)) + (0x9e)));
    static constexpr word const MusicHeaderOffsetData = word(((offsetof(G, MusicHeaderData)) - (1)));
    static constexpr word const MHD = word(offsetof(G, MusicHeaderData));
    static constexpr byte const A_Button = byte(0b10000000);
    static constexpr byte const B_Button = byte(0b1000000);
    static constexpr byte const Select_Button = byte(0b100000);
    static constexpr byte const Start_Button = byte(0b10000);
    static constexpr byte const Up_Dir = byte(0b1000);
    static constexpr byte const Down_Dir = byte(0b100);
    static constexpr byte const Left_Dir = byte(0b10);
    static constexpr byte const Right_Dir = byte(0b1);
    static constexpr byte const TitleScreenModeValue = byte(0);
    static constexpr byte const GameModeValue = byte(1);
    static constexpr byte const VictoryModeValue = byte(2);
    static constexpr byte const GameOverModeValue = byte(3);
};
