#!/bin/bash

exec                                        \
    clang++                                 \
    -g                                      \
    -o mario++                              \
    $@                                      \
    $(pkg-config --libs sfml-graphics)      \
