#!/bin/bash

CC=$1
if [[ ! -f "${CC}" ]]; then
    echo "not found: ${CC}"
    exit 1
fi

OBJ="${CC}.o"

pkg-config --exists --print-errors sfml-window || {
    echo "package 'sfml-window' required; doublecheck it's installed (and PKG_CONFIG_PATH is set)" ;
    exit 2 ;
}

exec                                    \
    clang++                             \
    -std=c++2b                          \
    -g                                  \
    -Wall                               \
    -Wextra                             \
    -Og                                 \
    -fno-inline                         \
    -fno-omit-frame-pointer             \
    -foptimize-sibling-calls            \
    $(pkg-config --cflags sfml-window)  \
    -o "${OBJ}"                         \
    -c "${CC}"
