#!/bin/bash

pkg-config --exists --print-errors sfml-graphics    || exit 2

echo "
-xc++
-std=c++2b
-g2
-Wall
-Wextra
-UNDEBUG
-foptimize-sibling-calls
"
echo $(pkg-config --cflags sfml-graphics) | tr ' ' $'\n'
