#!/bin/bash

pkg-config --exists --print-errors sfml-graphics    || exit 2

echo "
-std=c++23
-g1
-Wall
-Wextra
-Werror
-Wno-unused-command-line-argument
-O3
-march=native
-fno-rtti
-fno-exceptions
-fno-omit-frame-pointer
-momit-leaf-frame-pointer
-ffunction-sections
-fdata-sections
-UNDEBUG"
# -fsanitize=address
echo $(pkg-config --cflags sfml-graphics) | tr ' ' $'\n'

